name: MacOs Test

on:
  workflow_dispatch:


jobs:
  setup-p2s-vpn:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check Runner Public IP
      run: |
        brew update
        brew install --cask tuntap
        sudo kextload /Library/Extensions/tun.kext  
